ipmitool-xcat version 1.8.17 build tools
xcat2/xcat-dep pull request #11
Opened 2016-09-26 19:36 UTC by pdlun92

Added ipmitool-1.8.17 and necessary patches.  Modified build scripts and spec file accordingly

Addresses xcat-core issue #871 (https://github.com/xcat2/xcat-core/issues/871)

2016-09-26 23:48 UTC, daniceexi commented
@chenglch Please review this change.

2016-09-27 00:13 UTC, whowutwut requested changes

2016-09-27 00:13 UTC, whowutwut commented on ipmitool/ipmitool.spec
> +#Patch3:       ipmitool-%{version}-solactivate.patch
@pdlun92  I thought we had taken a look at this solactivate.patch and I thought we saw that it was included in 1.8.17 ,but now i'm looking at the source code and I don't see the following patch: 

https://github.com/xcat2/xcat-dep/blob/master/ipmitool/ipmitool-1.8.15-solactivate.patch

I don't see it in this file:  https://sourceforge.net/p/ipmitool/source/ci/IPMITOOL_1_8_17/tree/lib/ipmi_sol.c  

I think we need to create this new patch  `ipmitool-1.8.17-solactivate.patch` and rebuild the rpms.  :-( 

This is the thread that talks about it, but i thought I had seen a "target" for when this patch would be integrated,  I can't find it at this time.  https://sourceforge.net/p/ipmitool/mailman/message/34370504/

2016-09-27 00:13 UTC, whowutwut commented on ipmitool/ipmitool.spec
> +#%patch3 -p1
This would need uncomment if we are building the patch again.

2016-09-27 06:34 UTC, chenglch commented
To build the deb package, more change is needed in debian directory

2016-09-27 06:35 UTC, chenglch reviewed
To build the deb package, more change is needed in `debian` directory.

2016-09-27 06:35 UTC, chenglch commented on ipmitool/ipmitool.spec
> +#Patch3:       ipmitool-%{version}-solactivate.patch
I'm sure that the code in the solactivate.patch is not included in the 1.8.17 version.

2016-09-27 20:33 UTC, whowutwut approved these changes

2016-09-27 21:14 UTC, pdlun92 commented
@chenglch thanks for the comments.  What platforms should we build the debian packages on?

2016-09-28 00:58 UTC, chenglch commented
@pdlun92 , debian package is for ubuntu, if we do not support ubuntu system currently, it's ok

2016-09-28 02:50 UTC, whowutwut commented
I saw a 1.8.15-3 .deb package. Which OS should be used to build it?

2016-09-28 05:24 UTC, chenglch commented
Hi @whowutwut , ubuntu 14.04 system is used to build the deb package. We need some changes  and the symbol link files in the debian directory, then runs the `make_deb.sh` to build the deb package. We'd better try the deb package on ubuntu16.04 system to see if the package built on ubuntu14.04 woks well.

2016-09-28 05:45 UTC, chenglch commented
@whowutwut , this comment is not about this pull request, but some thought about our procedure to change or build the dependency, especially for ipmitool which is changed a little frequently these days. Actually, generating the  diff-patch files, synchronizing the upstream version and building the packages on various platforms, all of them are hard work. We'd better find a new way to solve these problems.

2016-09-28 09:14 UTC, zet809 commented
@whowutwut @pdlun92 Hi, victor and pat, I had noticed that the ipmitool-xcat-1.8.17 have been included in xcat-dep for Rh7, do you think we can ship it before doing a lot of verification with it? For example, rcons, rflash.

2016-09-28 13:30 UTC, whowutwut commented
@zet809  understand your concern.  There is a requirement for Garrison to be at ipmitool 1.8.17 level and 2.12.3 is planned for ESP.   I think we should make sure we update all our environment to use 1.8.17 in the next few days to make sure we flush out any issues.  Official support for those servers will be 2.12.4 and/or 2.13 release.

2016-09-29 00:37 UTC, daniceexi commented
If we need to use **ipmitool 1.8.17** for 2.12.3, please @tingtli and FVT team take some time to verify it for rh7.3 against FS and GRS server before the release manually.

2016-09-29 02:55 UTC, chenglch commented
For rhels is OK, I agree to merge

2016-09-29 02:55 UTC, merged